// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// core_model
Rcpp::List core_model(std::vector<double> ddt, std::vector<double> r1, std::vector<double> r2, std::vector<double> r3, std::vector<double> f4, const double& a0, const double& u0);
RcppExport SEXP _ALFAM2_core_model(SEXP ddtSEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP r3SEXP, SEXP f4SEXP, SEXP a0SEXP, SEXP u0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double> >::type ddt(ddtSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type r3(r3SEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type f4(f4SEXP);
    Rcpp::traits::input_parameter< const double& >::type a0(a0SEXP);
    Rcpp::traits::input_parameter< const double& >::type u0(u0SEXP);
    rcpp_result_gen = Rcpp::wrap(core_model(ddt, r1, r2, r3, f4, a0, u0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_ALFAM2_core_model", (DL_FUNC) &_ALFAM2_core_model, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_ALFAM2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
