# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

core_model <- function(ddt, r1, r2, r3, f4, a0, u0) {
    .Call('_ALFAM2_core_model', PACKAGE = 'ALFAM2', ddt, r1, r2, r3, f4, a0, u0)
}

